name: Check Redirects

on:
  workflow_dispatch:

jobs:
  check-redirects:
    runs-on: ubuntu-latest

    steps:
    - name: Print Start Time
      run: |
        START_DATE=$(TZ='Asia/Shanghai' date +'%Y年%m月%d日%H时%M分%S秒')
        echo "开始时间：$START_DATE"
    
    - name: Set DATE environment variable
      run: |
        echo "DATE=$(TZ='Asia/Shanghai' date +'%Y年%m月%d日%H时%M分')" >> $GITHUB_ENV
      
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install playwright
        python -m playwright install

    - name: Run redirect checker
      run: |
        python check_redirects.py

    - name: Check if results file is empty
      id: check_results
      run: |
        if [ ! -s check_results.md ]; then
          echo "results_empty=true" >> $GITHUB_ENV
        else
          echo "results_empty=false" >> $GITHUB_ENV
        fi
      
    - name: Commit results
      if: env.results_empty == 'false'
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          FILENAME="results/[手动检测]_$DATE.md"
        else
          FILENAME="results/[自动检测]_$DATE.md"
        fi
        mv check_results.md $FILENAME
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add $FILENAME
        git commit -m "Update check results for $DATE"
        git push
      env: 
        DATE: ${{ env.DATE }}
        
    - name: Print End Time
      run: |
        END_DATE=$(TZ='Asia/Shanghai' date +'%Y年%m月%d日%H时%M分%S秒')
        echo "结束时间：$END_DATE"
